// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LocationCreate
 */
export type LocationCreate = {
    /**
     * Raw Lat
     */
    raw_lat: number;
    /**
     * Raw Lng
     */
    raw_lng: number;
    /**
     * Landmark Text
     */
    landmark_text: string;
    /**
     * Commune
     */
    commune: string;
};

/**
 * LocationPublic
 */
export type LocationPublic = {
    /**
     * Landmark Text
     */
    landmark_text: string;
    /**
     * Commune
     */
    commune: string;
    /**
     * Raw Lat
     */
    raw_lat: number;
    /**
     * Raw Lng
     */
    raw_lng: number;
    /**
     * Id
     */
    id: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * OTPRequest
 */
export type OTPRequest = {
    /**
     * Phone Number
     */
    phone_number: string;
};

/**
 * OTPVerify
 */
export type OTPVerify = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Code
     */
    code: string;
};

/**
 * OrderCancel
 */
export type OrderCancel = {
    /**
     * Cancelled Reason
     */
    cancelled_reason?: string | null;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    location: LocationCreate;
    /**
     * Quantity Liters
     */
    quantity_liters: number;
    /**
     * Customer Phone
     */
    customer_phone?: string | null;
    /**
     * Requested Window Start
     */
    requested_window_start?: string | null;
    /**
     * Requested Window End
     */
    requested_window_end?: string | null;
};

/**
 * OrderPublic
 */
export type OrderPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Customer Id
     */
    customer_id: string | null;
    /**
     * Customer Phone
     */
    customer_phone: string;
    /**
     * Location Id
     */
    location_id: string;
    /**
     * Quantity Liters
     */
    quantity_liters: number;
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Total Price Dzd
     */
    total_price_dzd: string;
    status: OrderStatus;
    /**
     * Requested Window Start
     */
    requested_window_start: string | null;
    /**
     * Requested Window End
     */
    requested_window_end: string | null;
    /**
     * Confirmed By
     */
    confirmed_by: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Cancelled Reason
     */
    cancelled_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    location?: LocationPublic | null;
};

/**
 * OrderStatus
 */
export type OrderStatus = 'pending' | 'confirmed' | 'assigned' | 'en_route' | 'delivered' | 'cancelled';

/**
 * OrdersPublic
 */
export type OrdersPublic = {
    /**
     * Data
     */
    data: Array<OrderPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PricingCurrent
 */
export type PricingCurrent = {
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Effective From
     */
    effective_from?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * PricingSettingCreate
 */
export type PricingSettingCreate = {
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: number | string;
    /**
     * Effective From
     */
    effective_from?: string | null;
};

/**
 * PricingSettingPublic
 */
export type PricingSettingPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Effective From
     */
    effective_from: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'customer' | 'dispatcher' | 'driver' | 'admin';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type authRequestOtpData = {
    body: OTPRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/request';
};

export type authRequestOtpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authRequestOtpError = authRequestOtpErrors[keyof authRequestOtpErrors];

export type authRequestOtpResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authRequestOtpResponse = authRequestOtpResponses[keyof authRequestOtpResponses];

export type authVerifyOtpData = {
    body: OTPVerify;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/verify';
};

export type authVerifyOtpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authVerifyOtpError = authVerifyOtpErrors[keyof authVerifyOtpErrors];

export type authVerifyOtpResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authVerifyOtpResponse = authVerifyOtpResponses[keyof authVerifyOtpResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type ordersListOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: OrderStatus | null;
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/orders';
};

export type ordersListOrdersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersListOrdersError = ordersListOrdersErrors[keyof ordersListOrdersErrors];

export type ordersListOrdersResponses = {
    /**
     * Successful Response
     */
    200: OrdersPublic;
};

export type ordersListOrdersResponse = ordersListOrdersResponses[keyof ordersListOrdersResponses];

export type ordersCreateOrderData = {
    body: OrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/orders';
};

export type ordersCreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersCreateOrderError = ordersCreateOrderErrors[keyof ordersCreateOrderErrors];

export type ordersCreateOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersCreateOrderResponse = ordersCreateOrderResponses[keyof ordersCreateOrderResponses];

export type ordersReadOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: {
        /**
         * Phone
         */
        phone?: string | null;
    };
    url: '/api/v1/orders/{order_id}';
};

export type ordersReadOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersReadOrderError = ordersReadOrderErrors[keyof ordersReadOrderErrors];

export type ordersReadOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersReadOrderResponse = ordersReadOrderResponses[keyof ordersReadOrderResponses];

export type ordersConfirmOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_id}/confirm';
};

export type ordersConfirmOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersConfirmOrderError = ordersConfirmOrderErrors[keyof ordersConfirmOrderErrors];

export type ordersConfirmOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersConfirmOrderResponse = ordersConfirmOrderResponses[keyof ordersConfirmOrderResponses];

export type ordersCancelOrderData = {
    body: OrderCancel;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_id}/cancel';
};

export type ordersCancelOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersCancelOrderError = ordersCancelOrderErrors[keyof ordersCancelOrderErrors];

export type ordersCancelOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersCancelOrderResponse = ordersCancelOrderResponses[keyof ordersCancelOrderResponses];

export type pricingReadCurrentPricingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pricing/current';
};

export type pricingReadCurrentPricingResponses = {
    /**
     * Successful Response
     */
    200: PricingCurrent;
};

export type pricingReadCurrentPricingResponse = pricingReadCurrentPricingResponses[keyof pricingReadCurrentPricingResponses];

export type pricingCreatePricingData = {
    body: PricingSettingCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pricing';
};

export type pricingCreatePricingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type pricingCreatePricingError = pricingCreatePricingErrors[keyof pricingCreatePricingErrors];

export type pricingCreatePricingResponses = {
    /**
     * Successful Response
     */
    200: PricingSettingPublic;
};

export type pricingCreatePricingResponse = pricingCreatePricingResponses[keyof pricingCreatePricingResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];
