// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * CashReconciliationReport
 */
export type CashReconciliationReport = {
    /**
     * Date
     */
    date: string;
    /**
     * Rows
     */
    rows: Array<DriverCashRow>;
    /**
     * Total Expected Dzd
     */
    total_expected_dzd: string;
    /**
     * Total Collected Dzd
     */
    total_collected_dzd: string;
};

/**
 * DriverCashRow
 */
export type DriverCashRow = {
    /**
     * Driver Id
     */
    driver_id: string;
    /**
     * Driver Name
     */
    driver_name: string | null;
    /**
     * Driver Phone
     */
    driver_phone: string;
    /**
     * Delivered Stops
     */
    delivered_stops: number;
    /**
     * Expected Cash Dzd
     */
    expected_cash_dzd: string;
    /**
     * Collected Stops
     */
    collected_stops: number;
    /**
     * Collected Cash Dzd
     */
    collected_cash_dzd: string;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LocationCreate
 */
export type LocationCreate = {
    /**
     * Raw Lat
     */
    raw_lat: number;
    /**
     * Raw Lng
     */
    raw_lng: number;
    /**
     * Landmark Text
     */
    landmark_text: string;
    /**
     * Commune
     */
    commune: string;
};

/**
 * LocationPublic
 */
export type LocationPublic = {
    /**
     * Landmark Text
     */
    landmark_text: string;
    /**
     * Commune
     */
    commune: string;
    /**
     * Raw Lat
     */
    raw_lat: number;
    /**
     * Raw Lng
     */
    raw_lng: number;
    /**
     * Id
     */
    id: string;
};

/**
 * MaintenanceLogCreate
 */
export type MaintenanceLogCreate = {
    type: MaintenanceType;
    /**
     * Odometer Km At Event
     */
    odometer_km_at_event: number;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * MaintenanceLogPublic
 */
export type MaintenanceLogPublic = {
    type: MaintenanceType;
    /**
     * Odometer Km At Event
     */
    odometer_km_at_event: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Id
     */
    vehicle_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * MaintenanceType
 */
export type MaintenanceType = 'tire' | 'oil' | 'service' | 'other';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * OTPRequest
 */
export type OTPRequest = {
    /**
     * Phone Number
     */
    phone_number: string;
};

/**
 * OTPVerify
 */
export type OTPVerify = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Code
     */
    code: string;
};

/**
 * OrderCancel
 */
export type OrderCancel = {
    /**
     * Cancelled Reason
     */
    cancelled_reason?: string | null;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    location: LocationCreate;
    /**
     * Quantity Liters
     */
    quantity_liters: number;
    /**
     * Customer Phone
     */
    customer_phone?: string | null;
    /**
     * Requested Window Start
     */
    requested_window_start?: string | null;
    /**
     * Requested Window End
     */
    requested_window_end?: string | null;
};

/**
 * OrderPublic
 */
export type OrderPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Customer Id
     */
    customer_id: string | null;
    /**
     * Customer Phone
     */
    customer_phone: string;
    /**
     * Location Id
     */
    location_id: string;
    /**
     * Quantity Liters
     */
    quantity_liters: number;
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Total Price Dzd
     */
    total_price_dzd: string;
    status: OrderStatus;
    /**
     * Requested Window Start
     */
    requested_window_start: string | null;
    /**
     * Requested Window End
     */
    requested_window_end: string | null;
    /**
     * Confirmed By
     */
    confirmed_by: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Cancelled Reason
     */
    cancelled_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    location?: LocationPublic | null;
};

/**
 * OrderStatus
 */
export type OrderStatus = 'pending' | 'confirmed' | 'assigned' | 'en_route' | 'delivered' | 'cancelled';

/**
 * OrdersPublic
 */
export type OrdersPublic = {
    /**
     * Data
     */
    data: Array<OrderPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PendingMapPoint
 */
export type PendingMapPoint = {
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Raw Lat
     */
    raw_lat: number;
    /**
     * Raw Lng
     */
    raw_lng: number;
    /**
     * Customer Phone
     */
    customer_phone: string;
    /**
     * Quantity Liters
     */
    quantity_liters: number;
    /**
     * Landmark Text
     */
    landmark_text: string;
    /**
     * Commune
     */
    commune: string;
};

/**
 * PricingCurrent
 */
export type PricingCurrent = {
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Effective From
     */
    effective_from?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * PricingSettingCreate
 */
export type PricingSettingCreate = {
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: number | string;
    /**
     * Effective From
     */
    effective_from?: string | null;
};

/**
 * PricingSettingPublic
 */
export type PricingSettingPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Price Per Liter Dzd
     */
    price_per_liter_dzd: string;
    /**
     * Effective From
     */
    effective_from: string;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
    /**
     * Rating
     */
    rating: number;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Token
     */
    token?: string | null;
};

/**
 * ReviewPublic
 */
export type ReviewPublic = {
    /**
     * Rating
     */
    rating: number;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Customer Id
     */
    customer_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReviewsPublic
 */
export type ReviewsPublic = {
    /**
     * Data
     */
    data: Array<ReviewPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RouteCreate
 */
export type RouteCreate = {
    /**
     * Vehicle Id
     */
    vehicle_id: string;
    /**
     * Driver Id
     */
    driver_id: string;
    /**
     * Planned Date
     */
    planned_date: string;
    /**
     * Order Ids
     */
    order_ids: Array<string>;
};

/**
 * RoutePublic
 */
export type RoutePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Id
     */
    vehicle_id: string;
    /**
     * Driver Id
     */
    driver_id: string;
    /**
     * Planned Date
     */
    planned_date: string;
    status: RouteStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Stops
     */
    stops?: Array<RouteStopPublic>;
};

/**
 * RouteStatus
 */
export type RouteStatus = 'planned' | 'in_progress' | 'completed';

/**
 * RouteStopPublic
 */
export type RouteStopPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Route Id
     */
    route_id: string;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Sequence Number
     */
    sequence_number: number;
    /**
     * Delivered At
     */
    delivered_at: string | null;
    /**
     * Payment Collected
     */
    payment_collected: boolean;
    /**
     * Payment Collected At
     */
    payment_collected_at: string | null;
    order?: OrderPublic | null;
};

/**
 * RouteUpdate
 */
export type RouteUpdate = {
    status?: RouteStatus | null;
    /**
     * Order Ids
     */
    order_ids?: Array<string> | null;
};

/**
 * RoutesPublic
 */
export type RoutesPublic = {
    /**
     * Data
     */
    data: Array<RoutePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TelegramLinkCode
 */
export type TelegramLinkCode = {
    /**
     * Code
     */
    code: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * UserCreated
 */
export type UserCreated = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Telegram Linked
     */
    telegram_linked?: boolean;
    /**
     * Telegram Link Code
     */
    telegram_link_code?: string | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Telegram Linked
     */
    telegram_linked?: boolean;
};

/**
 * UserRole
 */
export type UserRole = 'customer' | 'dispatcher' | 'driver' | 'admin';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VehicleCreate
 */
export type VehicleCreate = {
    /**
     * Plate Number
     */
    plate_number: string;
    /**
     * Capacity Liters
     */
    capacity_liters: number;
    status?: VehicleStatus;
    /**
     * Current Odometer Km
     */
    current_odometer_km?: number;
};

/**
 * VehiclePublic
 */
export type VehiclePublic = {
    /**
     * Plate Number
     */
    plate_number: string;
    /**
     * Capacity Liters
     */
    capacity_liters: number;
    status?: VehicleStatus;
    /**
     * Current Odometer Km
     */
    current_odometer_km?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * VehicleStatus
 */
export type VehicleStatus = 'available' | 'on_route' | 'maintenance';

/**
 * VehicleUpdate
 */
export type VehicleUpdate = {
    /**
     * Plate Number
     */
    plate_number?: string | null;
    /**
     * Capacity Liters
     */
    capacity_liters?: number | null;
    status?: VehicleStatus | null;
    /**
     * Current Odometer Km
     */
    current_odometer_km?: number | null;
};

/**
 * VehiclesPublic
 */
export type VehiclesPublic = {
    /**
     * Data
     */
    data: Array<VehiclePublic>;
    /**
     * Count
     */
    count: number;
};

export type authRequestOtpData = {
    body: OTPRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/request';
};

export type authRequestOtpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authRequestOtpError = authRequestOtpErrors[keyof authRequestOtpErrors];

export type authRequestOtpResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authRequestOtpResponse = authRequestOtpResponses[keyof authRequestOtpResponses];

export type authVerifyOtpData = {
    body: OTPVerify;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/verify';
};

export type authVerifyOtpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authVerifyOtpError = authVerifyOtpErrors[keyof authVerifyOtpErrors];

export type authVerifyOtpResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authVerifyOtpResponse = authVerifyOtpResponses[keyof authVerifyOtpResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserCreated;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersReissueTelegramLinkCodeData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/telegram-link-code';
};

export type usersReissueTelegramLinkCodeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReissueTelegramLinkCodeError = usersReissueTelegramLinkCodeErrors[keyof usersReissueTelegramLinkCodeErrors];

export type usersReissueTelegramLinkCodeResponses = {
    /**
     * Successful Response
     */
    200: TelegramLinkCode;
};

export type usersReissueTelegramLinkCodeResponse = usersReissueTelegramLinkCodeResponses[keyof usersReissueTelegramLinkCodeResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type ordersListOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: OrderStatus | null;
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/orders';
};

export type ordersListOrdersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersListOrdersError = ordersListOrdersErrors[keyof ordersListOrdersErrors];

export type ordersListOrdersResponses = {
    /**
     * Successful Response
     */
    200: OrdersPublic;
};

export type ordersListOrdersResponse = ordersListOrdersResponses[keyof ordersListOrdersResponses];

export type ordersCreateOrderData = {
    body: OrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/orders';
};

export type ordersCreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersCreateOrderError = ordersCreateOrderErrors[keyof ordersCreateOrderErrors];

export type ordersCreateOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersCreateOrderResponse = ordersCreateOrderResponses[keyof ordersCreateOrderResponses];

export type ordersReadOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: {
        /**
         * Phone
         */
        phone?: string | null;
    };
    url: '/api/v1/orders/{order_id}';
};

export type ordersReadOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersReadOrderError = ordersReadOrderErrors[keyof ordersReadOrderErrors];

export type ordersReadOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersReadOrderResponse = ordersReadOrderResponses[keyof ordersReadOrderResponses];

export type ordersConfirmOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_id}/confirm';
};

export type ordersConfirmOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersConfirmOrderError = ordersConfirmOrderErrors[keyof ordersConfirmOrderErrors];

export type ordersConfirmOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersConfirmOrderResponse = ordersConfirmOrderResponses[keyof ordersConfirmOrderResponses];

export type ordersCancelOrderData = {
    body: OrderCancel;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_id}/cancel';
};

export type ordersCancelOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ordersCancelOrderError = ordersCancelOrderErrors[keyof ordersCancelOrderErrors];

export type ordersCancelOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type ordersCancelOrderResponse = ordersCancelOrderResponses[keyof ordersCancelOrderResponses];

export type dispatchPendingMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dispatch/pending-map';
};

export type dispatchPendingMapResponses = {
    /**
     * Response Dispatch-Pending Map
     *
     * Successful Response
     */
    200: Array<PendingMapPoint>;
};

export type dispatchPendingMapResponse = dispatchPendingMapResponses[keyof dispatchPendingMapResponses];

export type dispatchListRoutesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Planned Date
         */
        planned_date?: string | null;
    };
    url: '/api/v1/dispatch/routes';
};

export type dispatchListRoutesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dispatchListRoutesError = dispatchListRoutesErrors[keyof dispatchListRoutesErrors];

export type dispatchListRoutesResponses = {
    /**
     * Successful Response
     */
    200: RoutesPublic;
};

export type dispatchListRoutesResponse = dispatchListRoutesResponses[keyof dispatchListRoutesResponses];

export type dispatchCreateRouteData = {
    body: RouteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/dispatch/routes';
};

export type dispatchCreateRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dispatchCreateRouteError = dispatchCreateRouteErrors[keyof dispatchCreateRouteErrors];

export type dispatchCreateRouteResponses = {
    /**
     * Successful Response
     */
    200: RoutePublic;
};

export type dispatchCreateRouteResponse = dispatchCreateRouteResponses[keyof dispatchCreateRouteResponses];

export type dispatchUpdateRouteData = {
    body: RouteUpdate;
    path: {
        /**
         * Route Id
         */
        route_id: string;
    };
    query?: never;
    url: '/api/v1/dispatch/routes/{route_id}';
};

export type dispatchUpdateRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dispatchUpdateRouteError = dispatchUpdateRouteErrors[keyof dispatchUpdateRouteErrors];

export type dispatchUpdateRouteResponses = {
    /**
     * Successful Response
     */
    200: RoutePublic;
};

export type dispatchUpdateRouteResponse = dispatchUpdateRouteResponses[keyof dispatchUpdateRouteResponses];

export type driverTodaysRouteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/driver/routes/today';
};

export type driverTodaysRouteResponses = {
    /**
     * Response Driver-Todays Route
     *
     * Successful Response
     */
    200: RoutePublic | null;
};

export type driverTodaysRouteResponse = driverTodaysRouteResponses[keyof driverTodaysRouteResponses];

export type driverMarkDeliveredData = {
    body?: never;
    path: {
        /**
         * Stop Id
         */
        stop_id: string;
    };
    query?: never;
    url: '/api/v1/driver/stops/{stop_id}/delivered';
};

export type driverMarkDeliveredErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type driverMarkDeliveredError = driverMarkDeliveredErrors[keyof driverMarkDeliveredErrors];

export type driverMarkDeliveredResponses = {
    /**
     * Successful Response
     */
    200: RouteStopPublic;
};

export type driverMarkDeliveredResponse = driverMarkDeliveredResponses[keyof driverMarkDeliveredResponses];

export type driverMarkPaymentCollectedData = {
    body?: never;
    path: {
        /**
         * Stop Id
         */
        stop_id: string;
    };
    query?: never;
    url: '/api/v1/driver/stops/{stop_id}/payment-collected';
};

export type driverMarkPaymentCollectedErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type driverMarkPaymentCollectedError = driverMarkPaymentCollectedErrors[keyof driverMarkPaymentCollectedErrors];

export type driverMarkPaymentCollectedResponses = {
    /**
     * Successful Response
     */
    200: RouteStopPublic;
};

export type driverMarkPaymentCollectedResponse = driverMarkPaymentCollectedResponses[keyof driverMarkPaymentCollectedResponses];

export type fleetListVehiclesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/vehicles';
};

export type fleetListVehiclesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fleetListVehiclesError = fleetListVehiclesErrors[keyof fleetListVehiclesErrors];

export type fleetListVehiclesResponses = {
    /**
     * Successful Response
     */
    200: VehiclesPublic;
};

export type fleetListVehiclesResponse = fleetListVehiclesResponses[keyof fleetListVehiclesResponses];

export type fleetCreateVehicleData = {
    body: VehicleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles';
};

export type fleetCreateVehicleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fleetCreateVehicleError = fleetCreateVehicleErrors[keyof fleetCreateVehicleErrors];

export type fleetCreateVehicleResponses = {
    /**
     * Successful Response
     */
    200: VehiclePublic;
};

export type fleetCreateVehicleResponse = fleetCreateVehicleResponses[keyof fleetCreateVehicleResponses];

export type fleetUpdateVehicleData = {
    body: VehicleUpdate;
    path: {
        /**
         * Vehicle Id
         */
        vehicle_id: string;
    };
    query?: never;
    url: '/api/v1/vehicles/{vehicle_id}';
};

export type fleetUpdateVehicleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fleetUpdateVehicleError = fleetUpdateVehicleErrors[keyof fleetUpdateVehicleErrors];

export type fleetUpdateVehicleResponses = {
    /**
     * Successful Response
     */
    200: VehiclePublic;
};

export type fleetUpdateVehicleResponse = fleetUpdateVehicleResponses[keyof fleetUpdateVehicleResponses];

export type fleetAddMaintenanceLogData = {
    body: MaintenanceLogCreate;
    path: {
        /**
         * Vehicle Id
         */
        vehicle_id: string;
    };
    query?: never;
    url: '/api/v1/vehicles/{vehicle_id}/maintenance-logs';
};

export type fleetAddMaintenanceLogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fleetAddMaintenanceLogError = fleetAddMaintenanceLogErrors[keyof fleetAddMaintenanceLogErrors];

export type fleetAddMaintenanceLogResponses = {
    /**
     * Successful Response
     */
    200: MaintenanceLogPublic;
};

export type fleetAddMaintenanceLogResponse = fleetAddMaintenanceLogResponses[keyof fleetAddMaintenanceLogResponses];

export type pricingReadCurrentPricingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pricing/current';
};

export type pricingReadCurrentPricingResponses = {
    /**
     * Successful Response
     */
    200: PricingCurrent;
};

export type pricingReadCurrentPricingResponse = pricingReadCurrentPricingResponses[keyof pricingReadCurrentPricingResponses];

export type pricingCreatePricingData = {
    body: PricingSettingCreate;
    path?: never;
    query?: never;
    url: '/api/v1/pricing';
};

export type pricingCreatePricingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type pricingCreatePricingError = pricingCreatePricingErrors[keyof pricingCreatePricingErrors];

export type pricingCreatePricingResponses = {
    /**
     * Successful Response
     */
    200: PricingSettingPublic;
};

export type pricingCreatePricingResponse = pricingCreatePricingResponses[keyof pricingCreatePricingResponses];

export type reportsCashReconciliationData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date
         */
        date?: string | null;
    };
    url: '/api/v1/admin/reports/cash-reconciliation';
};

export type reportsCashReconciliationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reportsCashReconciliationError = reportsCashReconciliationErrors[keyof reportsCashReconciliationErrors];

export type reportsCashReconciliationResponses = {
    /**
     * Successful Response
     */
    200: CashReconciliationReport;
};

export type reportsCashReconciliationResponse = reportsCashReconciliationResponses[keyof reportsCashReconciliationResponses];

export type reviewsListReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Order Id
         */
        order_id?: string | null;
    };
    url: '/api/v1/reviews';
};

export type reviewsListReviewsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsListReviewsError = reviewsListReviewsErrors[keyof reviewsListReviewsErrors];

export type reviewsListReviewsResponses = {
    /**
     * Successful Response
     */
    200: ReviewsPublic;
};

export type reviewsListReviewsResponse = reviewsListReviewsResponses[keyof reviewsListReviewsResponses];

export type reviewsCreateReviewData = {
    body: ReviewCreate;
    path?: never;
    query?: never;
    url: '/api/v1/reviews';
};

export type reviewsCreateReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsCreateReviewError = reviewsCreateReviewErrors[keyof reviewsCreateReviewErrors];

export type reviewsCreateReviewResponses = {
    /**
     * Successful Response
     */
    200: ReviewPublic;
};

export type reviewsCreateReviewResponse = reviewsCreateReviewResponses[keyof reviewsCreateReviewResponses];

export type telegramTelegramWebhookData = {
    body?: never;
    headers?: {
        /**
         * X-Telegram-Bot-Api-Secret-Token
         */
        'x-telegram-bot-api-secret-token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/telegram/webhook';
};

export type telegramTelegramWebhookErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type telegramTelegramWebhookError = telegramTelegramWebhookErrors[keyof telegramTelegramWebhookErrors];

export type telegramTelegramWebhookResponses = {
    /**
     * Response Telegram-Telegram Webhook
     *
     * Successful Response
     */
    200: unknown;
};

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];
